import './globals.css'
import type { Metadata } from 'next'
import { Providers } from "./providers";
import { Footer, Header, LayoutContainer, Main } from '@/components/layoutComponents';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LayoutContainer>
            <Header />
            <Main>
              {children}
            </Main>
            <Footer />
          </LayoutContainer>
        </Providers>
      </body>
    </html>
  )
}
